name: nest

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.x
      - run: deno --version
      - name: Install eggs CLI
        run: |
          deno install -A -f --unstable -n eggs https://x.nest.land/eggs@0.1.8/mod.ts
      - name: Adding deno bin PATH
        run: |
          echo "::add-path::$HOME/.deno/bin"
      - name: Linking key
        env:
          NEST_KEY: ${{ secrets.NEST_KEY }}
        run: |
          eggs link --key $NEST_KEY
      - name: Publish update
        run: |
          eggs update

